services:
  db:
    image: postgres:16.0-alpine3.18
    restart: always
    ports:
      - "8394:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - groomroom-db-data-dev:/var/lib/postgresql/data

volumes:
  groomroom-db-data-dev: